Repository savvy-coders/sc-curriculum, pull requests merged in 2022-09, with the labels that each got.

#354 Rework section 4.2
  Section04/4.2-ArrayMethods1.md
Labels: enhancement

#364 Updated 7.2
  Section07/7.2-APIsAndAxios1.md
Labels: bug, against-master, high priority

#366 Update 7.2-APIsAndAxios1.md
  Section07/7.2-APIsAndAxios1.md
Labels: against-master
